id: A0EC459B1
title: Liberation Through Training in the Realm of Amitābha, Boundless Light
type: translation
pechas:
- I429A29D3
- I0B2ADAAC
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:02:00.098024
  last_modified_at: 2023-01-04 12:02:00.098038
  collections:
  - Jamgön Kongtrul Lodrö Thaye Series
  - Works of Tibetan Masters
alignment_to_base:
  I429A29D3/2791: DFFB
  I0B2ADAAC/C1F9: DFFB
